
services:
  # Test MongoDB instance
  mongodb-test:
    image: mongo:7.0
    container_name: mongodb-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
      MONGO_INITDB_DATABASE: healthcare-app-test
    ports:
      - "27018:27017"
    volumes:
      - mongodb-test-data:/data/db
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Test Backend API
  backend-test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-test
    environment:
      NODE_ENV: test
      PORT: 5001
      MONGODB_URI: mongodb://testuser:testpassword@mongodb-test:27017/healthcare-app-test?authSource=admin
    ports:
      - "5001:5001"
    depends_on:
      mongodb-test:
        condition: service_healthy
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...' &&
        sleep 15 &&
        node server/server.js
      "

  # Test Frontend (for integration tests)
  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-test
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://backend-test:5001/api
    depends_on:
      backend-test:
        condition: service_healthy
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: >
      sh -c "
        sed 's/backend-service:5000/backend-test:5001/g' /etc/nginx/conf.d/default.conf > /tmp/default.conf &&
        cp /tmp/default.conf /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'
      "

networks:
  test-network:
    driver: bridge

volumes:
  mongodb-test-data:
