apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-config
data:
  init-mongo.js: |
    // Create healthcare-app database and user
    db = db.getSiblingDB('healthcare-app');
    
    // Create a user for the application with appropriate permissions
    db.createUser({
      user: 'app-user',
      pwd: 'app-password',
      roles: [
        { role: 'readWrite', db: 'healthcare-app' }
      ]
    });
    
    // Create initial collections
    db.createCollection('appointments');
    
    // Insert some initial data if desired
    db.appointments.insertOne({
      title: 'Initial Checkup',
      description: 'General health checkup',
      image: 'https://example.com/images/checkup.jpg',
      address: '123 Medical Dr, Healthcare City, HC 12345',
      doctor: 'Dr. Jane Smith',
      doctorSpecialty: 'Family Medicine',
      clinicName: 'City Health Clinic',
      dateTime: new Date()
    });