apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: YWRtaW4= # admin (base64 encoded)
  mongodb-root-password: cGFzc3dvcmQxMjM= # password123 (base64 encoded)
  mongodb-connection-string: bW9uZ29kYjovL2FwcC11c2VyOmFwcC1wYXNzd29yZEBtb25nb2RiOjI3MDE3L2hlYWx0aGNhcmUtYXBw # mongodb://app-user:app-password@mongodb:27017/healthcare-app