apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
data:
  healthcare-alerts.yml: |
    groups:
    - name: healthcare.rules
      rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{namespace="healthcare"}[5m])) by (pod) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: "Pod {{ $labels.pod }} has high CPU usage (> 80% of requests) for more than 5 minutes."
      
      - alert: HighMemoryUsage
        expr: sum(container_memory_usage_bytes{namespace="healthcare"}) by (pod) / sum(kube_pod_container_resource_requests{namespace="healthcare", resource="memory"}) by (pod) > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: "Pod {{ $labels.pod }} is using more than 85% of its requested memory for more than 5 minutes."
      
      - alert: PodCrashLoopBackOff
        expr: kube_pod_container_status_waiting_reason{namespace="healthcare", reason="CrashLoopBackOff"} == 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Pod in CrashLoopBackOff state
          description: "Pod {{ $labels.pod }} is in CrashLoopBackOff state for more than 5 minutes."
      
      - alert: HighApiErrorRate
        expr: sum(rate(http_request_total{app="backend", status_code=~"5.."}[5m])) / sum(rate(http_request_total{app="backend"}[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: High API error rate
          description: "Backend API has a high error rate (> 5%) for more than 2 minutes."
      
      - alert: SlowApiResponse
        expr: rate(http_request_duration_seconds_sum{app="backend"}[5m])/rate(http_request_duration_seconds_count{app="backend"}[5m]) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow API response time
          description: "Backend API response time is greater than 2 seconds on average for more than 5 minutes."
      
      - alert: MongoDBDown
        expr: absent(up{job="mongodb"}) == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: MongoDB is down
          description: "MongoDB exporter is not reporting any metrics for more than 1 minute."
      
      - alert: BackendReplicasMismatch
        expr: kube_deployment_spec_replicas{deployment="backend", namespace="healthcare"} != kube_deployment_status_replicas_available{deployment="backend", namespace="healthcare"}
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Backend deployment replicas mismatch
          description: "Backend deployment has mismatch between requested and available replicas for more than 5 minutes."
      
      - alert: FrontendReplicasMismatch
        expr: kube_deployment_spec_replicas{deployment="frontend", namespace="healthcare"} != kube_deployment_status_replicas_available{deployment="frontend", namespace="healthcare"}
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Frontend deployment replicas mismatch
          description: "Frontend deployment has mismatch between requested and available replicas for more than 5 minutes."