config:
  target: 'http://backend-test:5001'
  phases:
    - duration: 30
      arrivalRate: 2
      name: "Ramp up"
    - duration: 60
      arrivalRate: 5
      name: "Sustained load"
    - duration: 30
      arrivalRate: 1
      name: "Cool down"
  processor: "./processor.js"
  timeout: 30

scenarios:
  - name: "Health Check"
    weight: 40
    flow:
      - get:
          url: "/health"
          expect:
            - statusCode: 200

  - name: "Get Appointments"
    weight: 40
    flow:
      - get:
          url: "/api/appointments"
          expect:
            - statusCode: 200

  - name: "Create Appointment"
    weight: 20
    flow:
      - post:
          url: "/api/appointments"
          json:
            patientName: "{{ $randomFullName() }}"
            doctorName: "Dr. {{ $randomLastName() }}"
            appointmentDate: "{{ $randomFutureDate() }}"
            description: "Load test appointment"
          expect:
            - statusCode: 201
