config:
  target: 'http://backend-test:5001'
  phases:
    - duration: 15
      arrivalRate: 1
      name: "Ramp up"
    - duration: 30
      arrivalRate: 2
      name: "Sustained load"
    - duration: 15
      arrivalRate: 1
      name: "Cool down"
  processor: "./processor.js"
  timeout: 15
  pool: 10

scenarios:
  - name: "Health Check"
    weight: 60
    flow:
      - get:
          url: "/health"
          expect:
            - statusCode: 200

  - name: "Get Appointments"
    weight: 30
    flow:
      - get:
          url: "/api/appointments"
          expect:
            - statusCode: 200

  - name: "Create Appointment"
    weight: 10
    flow:
      - post:
          url: "/api/appointments"
          json:
            patientName: "{{ $randomFullName() }}"
            doctorName: "Dr. {{ $randomLastName() }}"
            appointmentDate: "{{ $randomFutureDate() }}"
            description: "Load test appointment"
          expect:
            - statusCode: 201
